//import bcrypt from 'bcryptjs';
const data = {
  /* users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ], */
  products: [
    {
      _id: '612a259cfdbd356654bdadf5',
      code: 'B07MKRHFRT',
      title:
        "De'longhi Dinamica Ecam350.55.B - Cafetera superautom\u00e1tica, 1450w, funci\u00f3n cappuccino, personalizaci\u00f3n variedad de bebidas, panel de control intuitivo con pantalla lcd y botones t\u00e1ctiles, negro",
      details: [
        'Panel de control t\u00e1ctil con pantalla LCD',
        'LatteCrema System, prepara bebidas con leche autom\u00e1ticamente',
        'Funci\u00f3n de limpieza autom\u00e1tica integrada en deposito de leche y cafetera',
        'Funci\u00f3n "MY", memoriza bebidas personalizadas',
        'Funciona con caf\u00e9 en granos y con caf\u00e9 molido',
      ],
      name: 'Zodiac Polaris',
      slug: 'zodiac-polaris',
      category: 'Jardim',
      image: '/images/B07MKRHFRT/B07MKRHFRT0.jpg',
      isFeatured: true,
      featuredImage: '/images/B07MKRHFRT/B07MKRHFRT0.jpg',
      price: 315,
      brand: 'Zodiac',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Zodiac Polaris Vac-Sweep 280 Limpiafondos hidr√°ulico',
    },
    {
      _id: '612a259cfdbd356654bdadf7',
      code: 'B01JOYVGFK',
      title:
        'Cecotec Robot Aspirador Conga 5090. App con hasta 5 mapas. Aspira, Barre, Friega y Pasa la Mopa. Alexa y Google Assistant. Cepillo Jalisco. Cepillo para Mascotas. 8000 Pa. 10 Modos. Wi-Fi',
      details: [
        'Tecnolog\u00eda 4 in 1 con tanque mixto. El robot aspira, friega, barre y pasa la mopa. Adem\u00e1s es capaz de aspirar, barrer y pasar la mopa o fregar a la vez. Sistema BestFriend Care cepillo especial para mascotas. Cepillo Jalisco para una limpieza completa. Gracias a su sistema Total Surface 2.0 el robot cubrir\u00e1 toda la superficie recorrida. Conexi\u00f3n con redes Wi-Fi de 5 Ghz.',
        'Navegaci\u00f3n inteligente iTech Laser 360, mapea todo tu hogar y planifica la mejor ruta de limpieza. Sistema Force Clean con una potente turbina que maximiza la gran potencia de succi\u00f3n hasta 8000 Pa.',
        'Aplicaci\u00f3n para Smartphone. Cuenta con tres modos de fregado por control electr\u00f3nico aptos para cualquier tipo de superficie. Dise\u00f1ado con 10 modos de limpieza inteligente. Cuenta con el exclusivo sistema de fregado Scrubbing, para realizar un movimiento en vaiv\u00e9n. Contr\u00f3lalo con la m\u00e1xima comodidad desde su mando a distancia cuando no dispongas de Wi-Fi.',
        'Memoriza diferentes mapas y lo muestra en la APP. Con Room Plan podr\u00e1s editar y gestionar tus habitaciones y planes de limpieza personalizados. Sistema Turbo Clean Carpet especial para alfombras. Programable los 7 d\u00edas de la semana, 24 horas al d\u00eda.',
        'Conecta el robot con Alexa y Google Assistant. La limpieza por \u00e1reas o puntal permite seleccionar el punto exacto que quieras que limpie. Adem\u00e1s cuenta con la posibilidad de colocar \u00e1reas restringidas, para evitar que pase el robot.',
      ],
      name: 'Cecotec Robot Aspirador Conga 5090',
      slug: 'cecotec-robot-aspirador-conga-5090',
      category: 'Eletrodomesticos',
      image: '/images/B01JOYVGFK/B01JOYVGFK0.jpg',
      isFeatured: true,
      featuredImage: '/images/B01JOYVGFK/B01JOYVGFK0.jpg',
      price: 80,
      brand: 'Cecotec',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular robot',
    },
    {
      _id: '612a259cfdbd356654bdadf6',
      code: 'B0816VBBRT',
      title:
        "De'longhi Dinamica Ecam350.55.B - Cafetera superautom\u00e1tica, 1450w, funci\u00f3n cappuccino, personalizaci\u00f3n variedad de bebidas, panel de control intuitivo con pantalla lcd y botones t\u00e1ctiles, negro",
      details: [
        'Panel de control t\u00e1ctil con pantalla LCD',
        'LatteCrema System, prepara bebidas con leche autom\u00e1ticamente',
        'Funci\u00f3n de limpieza autom\u00e1tica integrada en deposito de leche y cafetera',
        'Funci\u00f3n "MY", memoriza bebidas personalizadas',
        'Funciona con caf\u00e9 en granos y con caf\u00e9 molido',
      ],
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/B0816VBBRT/B0816VBBRT0.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      _id: '612a259cfdbd356654bdadfa',
      code: 'B01JOYVGFK',
      title:
        "De'longhi Dinamica Ecam350.55.B - Cafetera superautom\u00e1tica, 1450w, funci\u00f3n cappuccino, personalizaci\u00f3n variedad de bebidas, panel de control intuitivo con pantalla lcd y botones t\u00e1ctiles, negro",
      details: [
        'Panel de control t\u00e1ctil con pantalla LCD',
        'LatteCrema System, prepara bebidas con leche autom\u00e1ticamente',
        'Funci\u00f3n de limpieza autom\u00e1tica integrada en deposito de leche y cafetera',
        'Funci\u00f3n "MY", memoriza bebidas personalizadas',
        'Funciona con caf\u00e9 en granos y con caf\u00e9 molido',
      ],
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/B0816VBBRT/B0816VBBRT0.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      _id: '612a259cfdbd356654bdadfb',
      code: 'B01JOYVGFK',
      title:
        "De'longhi Dinamica Ecam350.55.B - Cafetera superautom\u00e1tica, 1450w, funci\u00f3n cappuccino, personalizaci\u00f3n variedad de bebidas, panel de control intuitivo con pantalla lcd y botones t\u00e1ctiles, negro",
      details: [
        'Panel de control t\u00e1ctil con pantalla LCD',
        'LatteCrema System, prepara bebidas con leche autom\u00e1ticamente',
        'Funci\u00f3n de limpieza autom\u00e1tica integrada en deposito de leche y cafetera',
        'Funci\u00f3n "MY", memoriza bebidas personalizadas',
        'Funciona con caf\u00e9 en granos y con caf\u00e9 molido',
      ],
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/B0816VBBRT/B0816VBBRT0.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      _id: '612a259cfdbd356654bdadfc',
      code: 'B01JOYVGFK',
      title:
        "De'longhi Dinamica Ecam350.55.B - Cafetera superautom\u00e1tica, 1450w, funci\u00f3n cappuccino, personalizaci\u00f3n variedad de bebidas, panel de control intuitivo con pantalla lcd y botones t\u00e1ctiles, negro",
      details: [
        'Panel de control t\u00e1ctil con pantalla LCD',
        'LatteCrema System, prepara bebidas con leche autom\u00e1ticamente',
        'Funci\u00f3n de limpieza autom\u00e1tica integrada en deposito de leche y cafetera',
        'Funci\u00f3n "MY", memoriza bebidas personalizadas',
        'Funciona con caf\u00e9 en granos y con caf\u00e9 molido',
      ],
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/B0816VBBRT/B0816VBBRT0.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};
export default data;
